-- Banco: SQLite

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS CIDADE (
  ID_CIDADE   INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME        TEXT    NOT NULL,
  ESTADO      TEXT    NOT NULL CHECK(LENGTH(ESTADO) = 2)
);

CREATE TABLE IF NOT EXISTS PESSOA (
  ID_PESSOA   INTEGER PRIMARY KEY AUTOINCREMENT,
  NOME        TEXT    NOT NULL,
  TIPO        TEXT    NOT NULL CHECK(TIPO IN ('C','F','A')), -- Cliente, Fornecedor, Ambos
  CPF_CNPJ    TEXT    NOT NULL UNIQUE,
  EMAIL       TEXT,
  TELEFONE    TEXT,
  ENDERECO    TEXT,
  CEP         TEXT,
  ID_CIDADE   INTEGER REFERENCES CIDADE(ID_CIDADE)
);

-- CONTAS A PAGAR
CREATE TABLE IF NOT EXISTS CONTA_PAGAR (
  ID_PAGAR      INTEGER PRIMARY KEY AUTOINCREMENT,
  DT_EMISSAO    TEXT    NOT NULL,  -- ISO: YYYY-MM-DD
  VALOR_TOTAL   REAL    NOT NULL CHECK(VALOR_TOTAL > 0),
  ID_FORNECEDOR INTEGER NOT NULL REFERENCES PESSOA(ID_PESSOA),
  FINALIZADA    INTEGER NOT NULL DEFAULT 0 CHECK(FINALIZADA IN (0,1))
);

CREATE TABLE IF NOT EXISTS PARCELA_PAGAR (
  ID_PARCELA    INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_PAGAR      INTEGER NOT NULL REFERENCES CONTA_PAGAR(ID_PAGAR) ON DELETE CASCADE,
  NR_PARCELA    INTEGER NOT NULL,
  DT_VENCIMENTO TEXT    NOT NULL,
  VL_VENCIMENTO REAL    NOT NULL CHECK(VL_VENCIMENTO > 0),
  DT_PAGAMENTO  TEXT,
  VL_PAGAMENTO  REAL
);

-- CONTAS A RECEBER
CREATE TABLE IF NOT EXISTS CONTA_RECEBER (
  ID_RECEBER    INTEGER PRIMARY KEY AUTOINCREMENT,
  DT_EMISSAO    TEXT    NOT NULL,
  VALOR_TOTAL   REAL    NOT NULL CHECK(VALOR_TOTAL > 0),
  ID_CLIENTE    INTEGER NOT NULL REFERENCES PESSOA(ID_PESSOA),
  FINALIZADA    INTEGER NOT NULL DEFAULT 0 CHECK(FINALIZADA IN (0,1))
);

CREATE TABLE IF NOT EXISTS PARCELA_RECEBER (
  ID_PARCELA    INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_RECEBER    INTEGER NOT NULL REFERENCES CONTA_RECEBER(ID_RECEBER) ON DELETE CASCADE,
  NR_PARCELA    INTEGER NOT NULL,
  DT_VENCIMENTO TEXT    NOT NULL,
  VL_VENCIMENTO REAL    NOT NULL CHECK(VL_VENCIMENTO > 0),
  DT_RECEBIMENTO TEXT,
  VL_RECEBIMENTO REAL
);

-- ÍNDICES
CREATE INDEX IF NOT EXISTS IDX_PESSOA_TIPO     ON PESSOA(TIPO);
CREATE INDEX IF NOT EXISTS IDX_PESSOA_CPFCNPJ  ON PESSOA(CPF_CNPJ);
CREATE INDEX IF NOT EXISTS IDX_PAGAR_FORN      ON CONTA_PAGAR(ID_FORNECEDOR);
CREATE INDEX IF NOT EXISTS IDX_RECEBER_CLI     ON CONTA_RECEBER(ID_CLIENTE);
CREATE INDEX IF NOT EXISTS IDX_PARC_PAG        ON PARCELA_PAGAR(ID_PAGAR);
CREATE INDEX IF NOT EXISTS IDX_PARC_REC        ON PARCELA_RECEBER(ID_RECEBER);